PR changes requested
- `LOG_DEBUG` or `LOG_VERBOSE` do not change anything it they are unset (same as before)
- `LOG_DEBUG` or `LOG_VERBOSE` take precedence on Plex configuration file at start when set to `0` or `1`. The user can change the Preferences once the container is started which will overwrite the environment variables.

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -51,24 +51,24 @@ if [ ! -e "\$PREF_FILE" ]; then
     source gen-config.sh
 fi
 
-# Changes the log verbosity
-if [ "$LOGVERBOSE" = "1" ] || [ -z "$LOGVERBOSE" ]; then
+# Changes the log verbosity (Environment variable takes precedence on Plex Config)
+if [ "$LOG_VERBOSE" = "1" ]; then
     setPref "LogVerbose" "1"
-elif [ "$LOGVERBOSE" = "0" ]; then
+elif [ "$LOG_VERBOSE" = "0" ]; then
     setPref "LogVerbose" "0"
-else
-    2>&1 echo -e "${RED}LOGVERBOSE value '$LOGVERBOSE' is invalid${RESET}"
-    exit 0
+elif [ ! -z "$LOG_VERBOSE" ]; then
+    2>&1 echo -e "${RED}LOG_VERBOSE value '$LOG_VERBOSE' is invalid${RESET}"
+    exit 1
 fi
 
-# Changes the debug verbosity
-if [ "$LOGDEBUG" = "1" ] || [ -z "$LOGDEBUG" ]; then
+# Changes the debug verbosity (Environment variable takes precedence on Plex Config)
+if [ "$LOG_DEBUG" = "1" ]; then
     setPref "logDebug" "1"
-elif [ "$LOGDEBUG" = "0" ]; then
+elif [ "$LOG_DEBUG" = "0" ]; then
     setPref "logDebug" "0"
-else
-    2>&1 echo -e "${RED}LOGDEBUG value '$LOGDEBUG' is invalid${RESET}"
-    exit 0
+elif [ ! -z "$LOG_DEBUG" ]; then
+    2>&1 echo -e "${RED}LOG_DEBUG value '$LOG_DEBUG' is invalid${RESET}"
+    exit 1
 fi
 
 # Always attempt to claim an unclaimed server in case it was signed out
