Update image with adamant/busybox base image. No more patchelf and patching binaries on restart!

diff --git a/start_pms.patch b/start_pms.patch
--- a/start_pms.patch
+++ b/start_pms.patch
@@ -17,33 +17,35 @@
 -test -f /etc/default/plexmediaserver && . /etc/default/plexmediaserver
 +# Default values
 +export PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS="${PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS:-6}"
-+export PLEX_MEDIA_SERVER_HOME="${PLEX_MEDIA_SERVER_HOME:-<destdir>/plex-media-server}"
++export PLEX_MEDIA_SERVER_HOME="${PLEX_MEDIA_SERVER_HOME:-/usr/lib/plexmediaserver}"
 +export PLEX_MEDIA_SERVER_MAX_STACK_SIZE="${PLEX_MEDIA_SERVER_MAX_STACK_SIZE:-3000}"
 +export PLEX_MEDIA_SERVER_TMPDIR="${PLEX_MEDIA_SERVER_TMPDIR:-/tmp}"
 +export PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR="${PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR:-/config}"
 
  if [ ! -d "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR" ]
  then
-@@ -23,14 +17,17 @@
+@@ -22,15 +16,17 @@
+     exit 1
    fi
  fi
++if [ ! -w "$PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR" ]
++then
++  echo "ERROR: CANNOT WRITE IN $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR, MAKE SURE I HAVE PERMISSION TO DO THAT!"
++  exit 2
++fi
 
 -export LD_LIBRARY_PATH="${PLEX_MEDIA_SERVER_HOME}"
-+export LD_LIBRARY_PATH="${PLEX_MEDIA_SERVER_HOME}:${GLIBC_LIBRARY_PATH}"
++export LD_LIBRARY_PATH="${PLEX_MEDIA_SERVER_HOME}:$LD_LIBRARY_PATH"
  export TMPDIR="${PLEX_MEDIA_SERVER_TMPDIR}"
 
 -echo $PLEX_MEDIA_SERVER_MAX_PLUGIN_PROCS $PLEX_MEDIA_SERVER_MAX_STACK_SIZE $PLEX_MEDIA_SERVER_APPLICATION_SUPPORT_DIR
-+# Fix Locale, busybox doesn't care about it
-+export LANG=C
-+export LC_ALL=C
-
+-
 -ulimit -s $PLEX_MAX_STACK_SIZE
-+cd "$PLEX_MEDIA_SERVER_HOME"
-
+-
 -# Add sleep - Possible fix for start on boot.
 -sleep 3
-+if [ -f /config/plex/Plex\ Media\ Server/plexmediaserver.pid ]; then
-+    rm -f /config/plex/Plex\ Media\ Server/plexmediaserver.pid
++if [ -f /config/Plex\ Media\ Server/plexmediaserver.pid ]; then
++    rm -f /config/Plex\ Media\ Server/plexmediaserver.pid
 +fi
 
 -(cd /usr/lib/plexmediaserver; ./Plex\ Media\ Server)
